function H = correctJacobian(X,params)

%syms A B G L1 L2 h x y z
m = 2560; n = 2048;

x = X(1); y = X(2); z = X(3);
A = params(1); B = params(2); G = params(3); L1 = params(4); L2 = params(5); h = params(6);

%m = 4032; cx = 2016; % >
%n = 3024; cy = 1512; % ^

H = [ (L1*m*(y*(cos(G)*sin(A) - cos(A)*sin(B)*sin(G)) - (cos(A)*cos(G) + sin(A)*sin(B)*sin(G))*(h - z)))/(y*(cos(A)*sin(G) - cos(G)*sin(A)*sin(B)) + (sin(A)*sin(G) + cos(A)*cos(G)*sin(B))*(h - z) - x*cos(B)*cos(G)) - (L1*m*(y*(sin(A)*sin(G) + cos(A)*cos(G)*sin(B)) - (cos(A)*sin(G) - cos(G)*sin(A)*sin(B))*(h - z))*(y*(cos(A)*cos(G) + sin(A)*sin(B)*sin(G)) + (cos(G)*sin(A) - cos(A)*sin(B)*sin(G))*(h - z) + x*cos(B)*sin(G)))/(y*(cos(A)*sin(G) - cos(G)*sin(A)*sin(B)) + (sin(A)*sin(G) + cos(A)*cos(G)*sin(B))*(h - z) - x*cos(B)*cos(G))^2, (L1*m*(x*sin(B)*sin(G) + cos(A)*cos(B)*sin(G)*(h - z) - y*cos(B)*sin(A)*sin(G)))/(y*(cos(A)*sin(G) - cos(G)*sin(A)*sin(B)) + (sin(A)*sin(G) + cos(A)*cos(G)*sin(B))*(h - z) - x*cos(B)*cos(G)) + (L1*m*(x*cos(G)*sin(B) - y*cos(B)*cos(G)*sin(A) + cos(A)*cos(B)*cos(G)*(h - z))*(y*(cos(A)*cos(G) + sin(A)*sin(B)*sin(G)) + (cos(G)*sin(A) - cos(A)*sin(B)*sin(G))*(h - z) + x*cos(B)*sin(G)))/(y*(cos(A)*sin(G) - cos(G)*sin(A)*sin(B)) + (sin(A)*sin(G) + cos(A)*cos(G)*sin(B))*(h - z) - x*cos(B)*cos(G))^2,                                              L1*m + (L1*m*(y*(cos(A)*cos(G) + sin(A)*sin(B)*sin(G)) + (cos(G)*sin(A) - cos(A)*sin(B)*sin(G))*(h - z) + x*cos(B)*sin(G))^2)/(y*(cos(A)*sin(G) - cos(G)*sin(A)*sin(B)) + (sin(A)*sin(G) + cos(A)*cos(G)*sin(B))*(h - z) - x*cos(B)*cos(G))^2, -(m*(y*(cos(A)*cos(G) + sin(A)*sin(B)*sin(G)) + (cos(G)*sin(A) - cos(A)*sin(B)*sin(G))*(h - z) + x*cos(B)*sin(G)))/(y*(cos(A)*sin(G) - cos(G)*sin(A)*sin(B)) + (sin(A)*sin(G) + cos(A)*cos(G)*sin(B))*(h - z) - x*cos(B)*cos(G)),                                                                                                                                                                      0, (L1*m*(sin(A)*sin(G) + cos(A)*cos(G)*sin(B))*(y*(cos(A)*cos(G) + sin(A)*sin(B)*sin(G)) + (cos(G)*sin(A) - cos(A)*sin(B)*sin(G))*(h - z) + x*cos(B)*sin(G)))/(y*(cos(A)*sin(G) - cos(G)*sin(A)*sin(B)) + (sin(A)*sin(G) + cos(A)*cos(G)*sin(B))*(h - z) - x*cos(B)*cos(G))^2 - (L1*m*(cos(G)*sin(A) - cos(A)*sin(B)*sin(G)))/(y*(cos(A)*sin(G) - cos(G)*sin(A)*sin(B)) + (sin(A)*sin(G) + cos(A)*cos(G)*sin(B))*(h - z) - x*cos(B)*cos(G));
                                                                                                            (L2*n*(y*(sin(A)*sin(G) + cos(A)*cos(G)*sin(B)) - (cos(A)*sin(G) - cos(G)*sin(A)*sin(B))*(h - z))*(x*sin(B) - y*cos(B)*sin(A) + cos(A)*cos(B)*(h - z)))/(y*(cos(A)*sin(G) - cos(G)*sin(A)*sin(B)) + (sin(A)*sin(G) + cos(A)*cos(G)*sin(B))*(h - z) - x*cos(B)*cos(G))^2 - (L2*n*(y*cos(A)*cos(B) + cos(B)*sin(A)*(h - z)))/(y*(cos(A)*sin(G) - cos(G)*sin(A)*sin(B)) + (sin(A)*sin(G) + cos(A)*cos(G)*sin(B))*(h - z) - x*cos(B)*cos(G)),                                                                               (L2*n*(x*cos(B) + y*sin(A)*sin(B) - cos(A)*sin(B)*(h - z)))/(y*(cos(A)*sin(G) - cos(G)*sin(A)*sin(B)) + (sin(A)*sin(G) + cos(A)*cos(G)*sin(B))*(h - z) - x*cos(B)*cos(G)) - (L2*n*(x*cos(G)*sin(B) - y*cos(B)*cos(G)*sin(A) + cos(A)*cos(B)*cos(G)*(h - z))*(x*sin(B) - y*cos(B)*sin(A) + cos(A)*cos(B)*(h - z)))/(y*(cos(A)*sin(G) - cos(G)*sin(A)*sin(B)) + (sin(A)*sin(G) + cos(A)*cos(G)*sin(B))*(h - z) - x*cos(B)*cos(G))^2, -(L2*n*(x*sin(B) - y*cos(B)*sin(A) + cos(A)*cos(B)*(h - z))*(y*(cos(A)*cos(G) + sin(A)*sin(B)*sin(G)) + (cos(G)*sin(A) - cos(A)*sin(B)*sin(G))*(h - z) + x*cos(B)*sin(G)))/(y*(cos(A)*sin(G) - cos(G)*sin(A)*sin(B)) + (sin(A)*sin(G) + cos(A)*cos(G)*sin(B))*(h - z) - x*cos(B)*cos(G))^2,                                                                                                                                                                                                                                0, (n*(x*sin(B) - y*cos(B)*sin(A) + cos(A)*cos(B)*(h - z)))/(y*(cos(A)*sin(G) - cos(G)*sin(A)*sin(B)) + (sin(A)*sin(G) + cos(A)*cos(G)*sin(B))*(h - z) - x*cos(B)*cos(G)),                                                                                   (L2*n*cos(A)*cos(B))/(y*(cos(A)*sin(G) - cos(G)*sin(A)*sin(B)) + (sin(A)*sin(G) + cos(A)*cos(G)*sin(B))*(h - z) - x*cos(B)*cos(G)) - (L2*n*(sin(A)*sin(G) + cos(A)*cos(G)*sin(B))*(x*sin(B) - y*cos(B)*sin(A) + cos(A)*cos(B)*(h - z)))/(y*(cos(A)*sin(G) - cos(G)*sin(A)*sin(B)) + (sin(A)*sin(G) + cos(A)*cos(G)*sin(B))*(h - z) - x*cos(B)*cos(G))^2];
 
